import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { format } from "prettier";
import {
  buildContractManifest,
  duplicateOperationIds,
  mergeContractSchemaRegistries,
  missingSchemasForManifest,
} from "./index";
import {
  manifest as sourceGroundedBriefManifest,
  schemaRegistry as sourceGroundedBriefSchemaRegistry,
} from "../../../packages/convex/confect/capabilities/sourceGroundedBrief.spec";
import {
  manifest as brainPagesManifest,
  schemaRegistry as brainPagesSchemaRegistry,
} from "../../../packages/convex/confect/brain/pages.spec";

const functions = [...brainPagesManifest, ...sourceGroundedBriefManifest];
const schemaRegistry = mergeContractSchemaRegistries(
  brainPagesSchemaRegistry,
  sourceGroundedBriefSchemaRegistry,
);

const duplicateIds = duplicateOperationIds(functions);
if (duplicateIds.length > 0) {
  throw new Error(
    `Confect manifest operation ids must be unique: ${duplicateIds.join(", ")}`,
  );
}

const manifest = buildContractManifest(functions);

const missingSchemas = missingSchemasForManifest(manifest, schemaRegistry);
if (missingSchemas.length > 0) {
  throw new Error(
    `Confect manifest references schemas missing from registries: ${missingSchemas.join(", ")}`,
  );
}

const generatedRefModules: Readonly<Record<string, string>> = {
  "brain.pages": "packages/convex/convex/brain/pages.ts",
  "capabilities.sourceGroundedBrief":
    "packages/convex/convex/capabilities/sourceGroundedBrief.ts",
};

const escapeRegExp = (input: string): string =>
  input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const missingGeneratedRefs = manifest.functions.flatMap((entry) => {
  const modulePath = generatedRefModules[entry.namespace];
  if (modulePath === undefined) {
    return [`${entry.operationId} (no generated ref module configured)`];
  }

  const moduleSource = readFileSync(resolve(modulePath), "utf8");
  const exportPattern = new RegExp(
    `export\\s+const\\s+${escapeRegExp(entry.name)}\\s*=`,
  );

  return exportPattern.test(moduleSource) ? [] : [entry.operationId];
});

if (missingGeneratedRefs.length > 0) {
  throw new Error(
    `Confect manifest operations must have generated Convex refs. Run pnpm confect:codegen. Missing: ${missingGeneratedRefs.join(", ")}`,
  );
}

const target = resolve(
  "packages/template-core/src/generated/confectManifest.ts",
);
mkdirSync(dirname(target), { recursive: true });
const generated = await format(
  `/* Generated by pnpm confect:manifest. Do not edit by hand. */\n\nexport const confectManifest = ${JSON.stringify(manifest, null, 2)} as const;\n\nexport type ConfectManifest = typeof confectManifest;\n`,
  { parser: "typescript" },
);

writeFileSync(target, generated);
