import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { buildContractManifest, type ContractFunctionManifest } from "./index";

const functions: readonly ContractFunctionManifest[] = [
  {
    namespace: "brain.pages",
    name: "list",
    operationId: "brain.pages.list",
    kind: "query",
    surfaces: ["web"],
    typedErrors: ["Unauthorized", "MemberNotInWorkspace", "WorkspaceNotFound"],
    idempotent: true,
    argsSchemaName: "brain.pages.list.args",
    returnsSchemaName: "brain.pages.list.returns",
  },
  {
    namespace: "brain.pages",
    name: "createMarkdown",
    operationId: "brain.pages.createMarkdown",
    kind: "mutation",
    surfaces: ["web", "api", "cli", "mcp"],
    typedErrors: [
      "Unauthorized",
      "MemberNotInWorkspace",
      "WorkspaceNotFound",
      "ValidationFailed",
    ],
    idempotent: false,
    argsSchemaName: "brain.pages.createMarkdown.args",
    returnsSchemaName: "brain.pages.createMarkdown.returns",
  },
];

const manifest = buildContractManifest(functions);
const target = resolve(
  "packages/template-core/src/generated/confectManifest.ts",
);
mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  `/* Generated by pnpm confect:manifest. Do not edit by hand. */\n\nexport const confectManifest = ${JSON.stringify(manifest, null, 2)} as const;\n\nexport type ConfectManifest = typeof confectManifest;\n`,
);
